calidad:
    path:  /calidad
    defaults: { _controller: "CalidadBundle:Calidad:index" }

calidad_show:
    path:   /calidad/{id}/show
    defaults: { _controller: "CalidadBundle:Calidad:show" }

calidad_new:
    path:   /calidad/new
    defaults: { _controller: "CalidadBundle:Calidad:new" }

calidad_create:
    path:   /calidad/create
    defaults: { _controller: "CalidadBundle:Calidad:create" }
    requirements: { _method: post }

calidad_edit:
    path:   /calidad/{id}/edit
    defaults: { _controller: "CalidadBundle:Calidad:edit" }

calidad_update:
    path:   /calidad/{id}/update
    defaults: { _controller: "CalidadBundle:Calidad:update" }
    requirements: { _method: post|put }

calidad_delete:
    path:   /calidad/{id}/delete
    defaults: { _controller: "CalidadBundle:Calidad:delete" }
    requirements: { _method: post|delete }
    
calidad_by_id_delete:
    path:   /calidad/delete/{id}
    defaults: { _controller: "CalidadBundle:Calidad:deleteById" }
    requirements: { _method: get }
    

calidad_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "CalidadBundle:Calidad:bulk" }
    requirements: { _method: post }
    
