calidad:
    path:  /
    defaults: { _controller: "BackendBundle:Calidad:index" }

calidad_show:
    path:  /{id}/show
    defaults: { _controller: "BackendBundle:Calidad:show" }

calidad_new:
    path:  /new
    defaults: { _controller: "BackendBundle:Calidad:new" }

calidad_create:
    path:  /create
    defaults: { _controller: "BackendBundle:Calidad:create" }
    requirements: { _method: post }

calidad_edit:
    path:  /{id}/edit
    defaults: { _controller: "BackendBundle:Calidad:edit" }

calidad_update:
    path:  /{id}/update
    defaults: { _controller: "BackendBundle:Calidad:update" }
    requirements: { _method: post|put }

calidad_delete:
    path:  /{id}/delete
    defaults: { _controller: "BackendBundle:Calidad:delete" }
    requirements: { _method: post|delete }
    
calidad_by_id_delete:
    path:  /delete/{id}
    defaults: { _controller: "BackendBundle:Calidad:deleteById" }
    requirements: { _method: get }
    

calidad_bulk_action:
    path:  /bulk-action
    defaults: { _controller: "BackendBundle:Calidad:bulk" }
    requirements: { _method: post }
    
