app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /
app_homepage: 
        path: /
        defaults: { _controller: AppBundle:User:login } 
app_usuario:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix: /

