app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /
   
app_calidad:
    resource: "@AppBundle/Resources/config/routing/calidad.yml"
    prefix: /
    
app_general:
    resource: "@AppBundle/Resources/config/routing/general.yml"
    prefix: /
app_homepage: 
        path: /
        defaults: { _controller: AppBundle:Calidad:index } 
#    E