BackendBundle\Entity\Archivos:
    type: entity
    table: archivos
    indexes:
        fk_table1_usuario1:
            columns:
                - usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        archivo:
            type: string
            nullable: true
            length: 450
            options:
                fixed: false
        fechaCarga:
            type: datetime
            nullable: true
            column: fecha_carga
        tipo:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        nombrearchivo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
