BackendBundle\Entity\Config:
    type: entity
    table: config
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        txt:
            type: string
            nullable: true
            length: 400
            options:
                fixed: false
        pertenece:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
