BackendBundle\Entity\Ctacte:
    type: entity
    table: ctacte
    indexes:
        fk_ctacte_usuario1_idx:
            columns:
                - usuario_idusuario
        fk_ctacte_moviiento_idx:
            columns:
                - estado
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        movimiento:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        monto:
            type: integer
            nullable: true
            options:
                unsigned: false
        fechaingreso:
            type: datetime
            nullable: true
        fechavalidacion:
            type: datetime
            nullable: true
        codigocomprobante:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: codigoComprobante
    manyToOne:
        estado:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estado:
                    referencedColumnName: id
            orphanRemoval: false
        usuariousuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_idusuario:
                    referencedColumnName: idusuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
