BackendBundle\Entity\Documentos:
    type: entity
    table: documentos
    indexes:
        FK_proyecto:
            columns:
                - proyectoid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: '0'
        archivo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: '0'
    manyToOne:
        proyectoid:
            targetEntity: Proyectos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                proyectoid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
