BackendBundle\Entity\Fotos:
    type: entity
    table: fotos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idpallet:
            type: integer
            nullable: false
            options:
                unsigned: false
        foto:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
        tipo:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
