BackendBundle\Entity\Fotos:
    type: entity
    table: fotos
    indexes:
        FK_pallet_foto:
            columns:
                - idpallet
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        foto:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
        tipo:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
    manyToOne:
        idpallet:
            targetEntity: General
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idpallet:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
