BackendBundle\Entity\Fotos:
    type: entity
    table: fotos
    indexes:
        fk_fotos_calidad1_idx:
            columns:
                - calidad_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        foto:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
        tipo:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
    manyToOne:
        calidad:
            targetEntity: Calidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                calidad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
