BackendBundle\Entity\General:
    type: entity
    table: general
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        inspectorName:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: inspector_name
        numberPallet:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: number_pallet
        dateInspection:
            type: datetime
            nullable: true
            column: date_inspection
        inspectorPlanName:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: inspector_plan_name
        countryOrigin:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: country_origin
        commodityName:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: commodity_name
        variety:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: Variety
        productPackStyle:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: product_pack_style
        label:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        casesType:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: cases_type
        casesPerPallet:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: cases_per_pallet
        grower:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        size:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        packingDate:
            type: datetime
            nullable: true
            column: packing_date
        casesNetWeight:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: cases_net_weight
        barCodePlu:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: bar_code_plu
        costumer:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        shipper:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        lot:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        vasset:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        container:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        thier:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        comments:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        recommendation:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        fumigation:
            type: string
            nullable: true
            length: 450
            options:
                fixed: false
        fumigationSo2:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: fumigation_so2
        organic:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        palletType:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: pallet_type
        clamshellPerCases:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: clamshell_per_cases
        grade:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        temperature:
            type: float
            nullable: true
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
