BackendBundle\Entity\Movimientos:
    type: entity
    table: movimientos
    indexes:
        fk_monimientos_usuario1_idx:
            columns:
                - usuario_idusuario
        fk_monimientos_proyectos1_idx:
            columns:
                - proyectos_id
        fk_movimientos_tipoaccion_idx:
            columns:
                - tipoaccion
        fk_movimientos_usrdestino_idx:
            columns:
                - usrdestino
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        readed:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        acciones:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    oneToOne:
        proyectos:
            targetEntity: Proyectos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                proyectos_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuariousuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_idusuario:
                    referencedColumnName: idusuario
            orphanRemoval: false
    manyToOne:
        tipoaccion:
            targetEntity: Config
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipoaccion:
                    referencedColumnName: id
            orphanRemoval: false
        usrdestino:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usrdestino:
                    referencedColumnName: idusuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
