BackendBundle\Entity\Pagos:
    type: entity
    table: pagos
    indexes:
        fk_pagos_proyectos1_idx:
            columns:
                - proyectos_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: datetime
            nullable: true
        monto:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        proyectos:
            targetEntity: Proyectos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                proyectos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
