BackendBundle\Entity\Proyectos:
    type: entity
    table: proyectos
    uniqueConstraints:
        codigo:
            columns:
                - codigo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 400
            options:
                fixed: false
        direccion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        proyeccion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        uf:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: UF
        acciones:
            type: integer
            nullable: true
            options:
                unsigned: false
        valor:
            type: integer
            nullable: true
            options:
                unsigned: false
        vendidas:
            type: integer
            nullable: true
            options:
                unsigned: false
        cop:
            type: integer
            nullable: true
            options:
                unsigned: false
        fechaCompraEst:
            type: date
            nullable: true
            column: fecha_compra_est
    lifecycleCallbacks: {  }
