BackendBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
