BackendBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        app:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        apm:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        role:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        correo:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
