backend_calidad:
    resource: "@BackendBundle/Resources/config/routing/calidad.yml"
    prefix:   /calidad

backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
