backend_condicion:
    resource: "@BackendBundle/Resources/config/routing/condicion.yml"
    prefix:   /condicion



backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
